### ISSUE TITLE
profit fails in nrtplot

### ISSUE THREAD

**Issue by vikdhillon** [HiPERCAM/hipercam#125]
profit in nrtplot fails with the error below. I tried fitting just one star on one CCD, and in all CCDs, but the same error occurs. I also tried playing around with the profit parameters by typing nrtplot prompt, but no luck. I'm pretty sure profit in nrtplot was working ok the last time I tried it (a few weeks ago?), so it is likely due to a recent change?

Traceback (most recent call last):
  File "/usr/local/python-3.11.4/bin/nrtplot", line 8, in <module>
    sys.exit(nrtplot())
             ^^^^^^^^^
  File "/usr/local/python-3.11.4/lib/python3.11/site-packages/hipercam/scripts/nrtplot.py", line 1210, in nrtplot
    imanager.update()
  File "/usr/local/python-3.11.4/lib/python3.11/site-packages/hipercam/scripts/nrtplot.py", line 1562, in update
    self.targ_artists = self._disp_targs(self.targ_artists)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python-3.11.4/lib/python3.11/site-packages/hipercam/scripts/nrtplot.py", line 1691, in _disp_targs
    dot.set_data(fpar.x, fpar.y)
  File "/usr/local/python-3.11.4/lib/python3.11/site-packages/matplotlib/lines.py", line 665, in set_data
    self.set_xdata(x)
  File "/usr/local/python-3.11.4/lib/python3.11/site-packages/matplotlib/lines.py", line 1289, in set_xdata
    raise RuntimeError('x must be a sequence')
RuntimeError: x must be a sequence

**Comment by StuartLittlefair** [comment]
fixed in https://github.com/HiPERCAM/hipercam/commit/5d9dcd6f66826693b61c32e25b912fbb2220e986

This was an API change in Matplotlib 3.7. I think we must have jumped from 3.6 to 3.9 which is why we did not see the changes
