### ISSUE TITLE
Copy apertures option in setaper doesn't seem to work

### ISSUE THREAD

**Issue by vikdhillon** [HiPERCAM/hipercam#23]
The copy option in setaper fails with the following error:

a(dd), b(reak), c(entre), d(elete), e(xtra) h(elp),  l(ink), m(ask), p(rofit), q(uit), r(eference), C(opy): c
  fitting ...
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/matplotlib/cbook/__init__.py", line 388, in process
    proxy(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/matplotlib/cbook/__init__.py", line 228, in __call__
    return mtd(*args, **kwargs)
  File "/home/observer/.local/lib/python3.5/site-packages/hipercam/scripts/setaper.py", line 601, in _keyPressEvent
    self._standard(event.key, event.xdata, event.ydata, event.inaxes)
  File "/home/observer/.local/lib/python3.5/site-packages/hipercam/scripts/setaper.py", line 679, in _standard
    self._centre()
  File "/home/observer/.local/lib/python3.5/site-packages/hipercam/scripts/setaper.py", line 937, in _centre
    (X, Y, message) = hcam.combFit(
AttributeError: module 'hipercam' has no attribute 'combFit'

**Comment by trmrsh** [comment]
This was actually the "centre" option for re-centering apertures, although it was a bug nonetheless. I have fixed it anyhow, and I checked that 'Copy" works.
