### ISSUE TITLE
hplot with ccd=0 doesn't work with full frame with overscan

### ISSUE THREAD

**Issue by vikdhillon** [HiPERCAM/hipercam#29]
hplot works fine with full frame with overscan when plotting a single CCD, but fails when trying to plot all 5 - see below:

hipercam{observer}135: hplot
input - frame to plot [run0036_004]: 
ccd - CCD(s) to plot [0 for all] [5]: 
msub - subtract median from each window? [True]: \
CCD = 5 plot range = -10.0 to 7.0

Click points in windows for stats in a 21x21 box
hipercam{observer}136: hplot
input - frame to plot [run0036_004]: 
ccd - CCD(s) to plot [0 for all] [5]: 1
msub - subtract median from each window? [True]: \
CCD = 1 plot range = -9.0 to 6.0

Click points in windows for stats in a 21x21 box
hipercam{observer}137: hplot
input - frame to plot [run0036_004]: 
ccd - CCD(s) to plot [0 for all] [1]: 0
nx - number of panels in X [2]: \
CCD = 1 plot range = -9.0 to 6.0
CCD = 2 plot range = -10.0 to 7.0
CCD = 3 plot range = -9.0 to 7.0
CCD = 4 plot range = -10.0 to 7.0
CCD = 5 plot range = -10.0 to 7.0
Traceback (most recent call last):
  File "/home/observer/.local/bin/hplot", line 11, in <module>
    load_entry_point('hipercam==0.7.dev7+g994a2b5', 'console_scripts', 'hplot')()
  File "/home/observer/.local/lib/python3.5/site-packages/hipercam/scripts/hplot.py", line 257, in hplot
    plt.tight_layout()
  File "/usr/local/lib/python3.5/dist-packages/matplotlib/pyplot.py", line 1366, in tight_layout
    fig.tight_layout(pad=pad, h_pad=h_pad, w_pad=w_pad, rect=rect)
  File "/usr/local/lib/python3.5/dist-packages/matplotlib/figure.py", line 2275, in tight_layout
    pad=pad, h_pad=h_pad, w_pad=w_pad, rect=rect)
  File "/usr/local/lib/python3.5/dist-packages/matplotlib/tight_layout.py", line 328, in get_tight_layout_figure
    pad=pad, h_pad=h_pad, w_pad=w_pad)
  File "/usr/local/lib/python3.5/dist-packages/matplotlib/tight_layout.py", line 114, in auto_adjust_subplotpars
    tight_bbox_raw = union([ax.get_tightbbox(renderer) for ax in subplots
  File "/usr/local/lib/python3.5/dist-packages/matplotlib/tight_layout.py", line 115, in <listcomp>
    if ax.get_visible()])
  File "/usr/local/lib/python3.5/dist-packages/matplotlib/axes/_base.py", line 4159, in get_tightbbox
    self.apply_aspect()
  File "/usr/local/lib/python3.5/dist-packages/matplotlib/axes/_base.py", line 1631, in apply_aspect
    raise RuntimeError("adjustable='datalim' is not allowed when both"
RuntimeError: adjustable='datalim' is not allowed when both axes are shared.
hipercam{observer}138:

**Comment by trmrsh** [comment]
Shutting this one as I think it is no longer relevant
