### ISSUE TITLE
KeyError using reduce with Ultracam

### ISSUE THREAD

**Issue by matthu7777** [HiPERCAM/hipercam#50]
Crashed at one point when we were using Ultracam. Worked first time, then when we moved the apertures and tried to re-reduce the reduction failed with the error message below. We found that by deleting and remaking both '.ape' and '.red' files we could fix it.

Traceback (most recent call last):
  File "/home/observer/.local/bin/reduce", line 11, in <module>
    sys.exit(reduce())
  File "/home/observer/.local/lib/python3.4/site-packages/hipercam/scripts/reduce.py", line 914, in reduce
    replot, ltmax = plotLight(lpanel, t, results, rfile, tkeep, lbuffer)
  File "/home/observer/.local/lib/python3.4/site-packages/hipercam/scripts/reduce.py", line 2442, in plotLight
    f = lc.add_point(t, results)
  File "/home/observer/.local/lib/python3.4/site-packages/hipercam/scripts/reduce.py", line 2674, in add_point
    targ = res[self.targ]
KeyError: '3'

**Comment by trmrsh** [comment]
Fundamentally a simply error (attempt to access a non-existent dictionary key), unfortunately as the files that caused it were deleted, I cannot easily diagnose it. Please see if you can repeat it. I am unsure what you mean by "move" the apertures. A guess is that you could have ended up with an aperture file without an aperture number 3 having created a reduce file that referred to aperture 3. Is this likely? I could put some extra checks in reduce to quite early in such cases and report a more helpful message.

**Comment by matthu7777** [comment]
Will try to reproduce. By 'move' I mean that we deleted one of the apertures and replaced it on a different star. I don't believe that we changed the number of apertures at all, and there should only have been 2. But it might be possible that we put 3 the first time by accident.

**Comment by trmrsh** [comment]
I'll probably try to implement some checks. It certainly thought that there was an aperture '3', but this should be something I can look for and generate a friendlier message. It might have been that you at one point created 3 apertures, then deleted one of them leaving apertures 1 & 3 when you generated the reduce file. If you deleted and re-created aperture 3, it would have been replaced by aperture 2. That would caused problems.
