### ISSUE TITLE
reduce fails at start of drift mode reduction

### ISSUE THREAD

**Issue by vikdhillon** [HiPERCAM/hipercam#56]
Reducing run0014 on 2018_10_04, a 100Hz drift mode run, works fine if first>=3, but fails with the error below if first=1 or 2. Note that the star is visible in frame=1 and frame=2:

hipercam{observer}224: reduce first=2 \\
Frame 2: 2018-10-04T20:44:30.4279861 [NOK]
/home/observer/.local/lib/python3.5/site-packages/hipercam/reduction.py:992: UserWarning: '** fit_half_width' < 5*max(xbin,ybin) (24.0 vs 40) ==> small windows for profile fits. Advise increasing its value in the reduce file if possible.
  rfile['apertures']['fit_half_width'], 5*max(xbin, ybin)
Traceback (most recent call last):
  File "/home/observer/.local/bin/reduce", line 11, in <module>
    sys.exit(reduce())
  File "/home/observer/.local/lib/python3.5/site-packages/hipercam/scripts/reduce.py", line 419, in reduce
    tkeep, lbuffer, xbuffer, ybuffer, tbuffer, sbuffer
  File "/home/observer/.local/lib/python3.5/site-packages/hipercam/reduction.py", line 765, in update_plots
    replot, ltmax = plotLight(lpanel, t, results, rfile, tkeep, lbuffer)
  File "/home/observer/.local/lib/python3.5/site-packages/hipercam/reduction.py", line 2125, in plotLight
    f = lc.add_point(t, results)
  File "/home/observer/.local/lib/python3.5/site-packages/hipercam/reduction.py", line 2363, in add_point
    if self.cnam not in results:
TypeError: argument of type 'NoneType' is not iterable
hipercam{observer}225:

**Comment by trmrsh** [comment]
I hope I have fixed this one. Re-open if not
