### ISSUE TITLE
astropy 4.0

### ISSUE THREAD

**Issue by paulkerry1** [HiPERCAM/hipercam#76]
Using the newly released astropy 4.0, rtplot and reduce both fail for ultracam data (using run015 from 2019_12_02). rtplot and reduce work with hipercam and ultraspec data.

`rtplot \\
Traceback (most recent call last):
  File "/usr/local/bin/rtplot", line 8, in <module>
    sys.exit(rtplot())
  File "/usr/local/lib/python3.7/dist-packages/hipercam/scripts/rtplot.py", line 554, in rtplot
    for mccd in spool:
  File "/usr/local/lib/python3.7/dist-packages/hipercam/spooler.py", line 114, in __next__
    return self._iter.__next__()
  File "/usr/local/lib/python3.7/dist-packages/hipercam/ucam.py", line 656, in __next__
    return self.__call__()
  File "/usr/local/lib/python3.7/dist-packages/hipercam/ucam.py", line 1149, in __call__
    super().copy()
  File "/usr/local/lib/python3.7/dist-packages/astropy/io/fits/header.py", line 823, in copy
    tmp = self.__class__((copy.copy(card) for card in self._cards))
  File "/usr/local/lib/python3.7/dist-packages/hipercam/ucam.py", line 625, in __init__
    Rhead.__init__(self, run, server)
  File "/usr/local/lib/python3.7/dist-packages/hipercam/ucam.py", line 147, in __init__
    udom = xml.dom.minidom.parse(run + '.xml')
TypeError: unsupported operand type(s) for +: 'generator' and 'str'
`
Using astropy==3.2.3 works perfectly.

Cheers
Paul.

**Comment by trmrsh** [comment]
Dear Paul, finally got onto this one. Quite a nasty one actually, anyway it made me realise I hadn't quite completed some changes I made last year to remove astropy FITS header objects from parts of the code. Anyway I think I have fixed it. Once I have carried out a few more tests, I will stick the changes into the master branch, and let you know by closing out this issue. Tom

**Comment by trmrsh** [comment]
Hi Paul, OK, my fixes seem to work, so I have put them onto the master branch and will close this issue. I have defined a version tag 0.19.8 which I have also pushed to github. I recommend that you install this version at both the NTT and TNT. Tom
