### ISSUE TITLE
Setaper crashes if you try to centre a linked aperture

### ISSUE THREAD

**Issue by SGParsons** [HiPERCAM/hipercam#77]
Setaper will crash if you try to centre an aperture that is linked to another aperture. Obviously this is something that you shouldn't be doing (i.e. you should re-centre the main aperture and that automatically re-centres all linked apertures) but its annoying that the program crashes if you accidentally centre on the wrong aperture, meaning that you need to start all your apertures again!

**Comment by trmrsh** [comment]
Tried to replicate but failed. It certainly raises an error, but does not crash. e.g. I got as appended below. Please try to replicate this, tell me exactly how it happend and the result. Cheers.

Traceback (most recent call last):
  File "/warwick/desktop/2018/software/MPI/GCC/7.3.0-2.30/OpenMPI/3.1.1/matplotlib/3.0.0-Python-3.6.6/lib/python3.6/site-packages/matplotlib/cbook/__init__.py", line 215, in process
    func(*args, **kwargs)
  File "/home/astro/phsaap/.local/lib/python3.6/site-packages/hipercam/scripts/setaper.py", line 665, in _keyPressEvent
    self._standard(event.key, event.xdata, event.ydata, event.inaxes)
  File "/home/astro/phsaap/.local/lib/python3.6/site-packages/hipercam/scripts/setaper.py", line 743, in _standard
    self._centre()
  File "/home/astro/phsaap/.local/lib/python3.6/site-packages/hipercam/scripts/setaper.py", line 1020, in _centre
    self._axes, aper, apnam)
  File "/home/astro/phsaap/.local/lib/python3.6/site-packages/hipercam/mpl.py", line 258, in pAper
    'to plot a linked aperture, need to pass through an CcdAper'
ValueError: to plot a linked aperture, need to pass through an CcdAper
