### ISSUE TITLE
setaper cannot "centre" apertures.

### ISSUE THREAD

**Issue by StuartLittlefair** [HiPERCAM/hipercam#85]
To reproduce, hover over an aperture and click `c`:

```python
  fitting ...
  initial search returned x, y, peak = 914.5, 354.5, 658.90966796875
Traceback (most recent call last):
  File "/Users/sl/mambaforge/envs/py38/lib/python3.8/site-packages/matplotlib/cbook/__init__.py", line 224, in process
    func(*args, **kwargs)
  File "/Users/sl/mambaforge/envs/py38/lib/python3.8/site-packages/hipercam/scripts/setaper.py", line 785, in _keyPressEvent
    self._standard(event.key, event.xdata, event.ydata, event.inaxes)
  File "/Users/sl/mambaforge/envs/py38/lib/python3.8/site-packages/hipercam/scripts/setaper.py", line 865, in _standard
    self._centre()
  File "/Users/sl/mambaforge/envs/py38/lib/python3.8/site-packages/hipercam/scripts/setaper.py", line 1176, in _centre
    sigma = np.sqrt(self.read2**2 + np.maximum(0,fwind.data)/self.gain)
AttributeError: 'PickStar' object has no attribute 'read2'
```

**Comment by trmrsh** [comment]
Fixed, but will fix the rupdate issue before releasing changes.
